[System.Serializable]
public class WorldData
{
    public string uid;
    public string version;

    public string worldName;
    public int seed;

    public bool worldGenSettingsGenerated = false;

    public WorldSettings worldSettings;
    public WorldGenSettings worldGenSettings; // Will be generated by World.cs and saved here

    /// <summary>
    /// WorldBiomes saves the index of all the biomes starting from 0 in a specific order.
    /// When new biomes are added in updates, they will be added to the end of the list.
    /// The order of the biomes in this list is important for the world generation.
    /// </summary>
    public WorldBiomes worldBiomes;
}