[System.Serializable]
public class WorldData
{
    public string worldName;
    public int seed;

    public bool worldGenSettingsGenerated = false;

    public WorldSettings worldSettings;
    public WorldGenSettings worldGenSettings; // Will be generated by World.cs and saved here
}